import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: '程序开发笔记',
      link: {type: 'doc', id: 'dev-notes/index'},
      items: [{type: 'autogenerated', dirName: 'dev-notes'}],
    },
    {
      type: 'category',
      label: 'UE5 踩坑记录',
      link: {type: 'doc', id: 'ue5-caveats/index'},
      items: [{type: 'autogenerated', dirName: 'ue5-caveats'}],
    },
    {
      type: 'category',
      label: '游戏世界观',
      link: {type: 'doc', id: 'world-building/index'},
      items: [
        {type: 'autogenerated', dirName: 'world-building/lore'},
        {type: 'autogenerated', dirName: 'world-building/factions'},
        {type: 'autogenerated', dirName: 'world-building/geography'},
        {type: 'autogenerated', dirName: 'world-building/characters'},
      ],
    },
    {
      type: 'category',
      label: '项目管理',
      link: {type: 'doc', id: 'project-mgmt/index'},
      items: [{type: 'autogenerated', dirName: 'project-mgmt'}],
    },
    {
      type: 'category',
      label: '大型网游开发',
      link: {type: 'doc', id: 'mmo-dev/index'},
      items: [{type: 'autogenerated', dirName: 'mmo-dev'}],
    },
    {
      type: 'category',
      label: '游戏设计分析',
      link: {type: 'doc', id: 'game-design-analysis/index'},
      items: [{type: 'autogenerated', dirName: 'game-design-analysis'}],
    },
  ],
};

export default sidebars;
